# Generated by Django 2.2.2 on 2021-10-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ajax', '0003_auto_20211002_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welbex',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
